services:
  mysql:
    image: mysql:8.0
    container_name: powertrack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: powertrack_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: powertrack-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data: